apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-notifier-green
  labels:
    app: job-notifier
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-notifier
      version: green
  template:
    metadata:
      labels:
        app: job-notifier
        version: green
    spec:
      containers:
        - name: job-notifier
          image: 425999196557.dkr.ecr.us-east-1.amazonaws.com/qa/job-notifier:latest
          ports:
            - containerPort: 5500
          envFrom:
            - secretRef:
                name: job-secrets

